language: node_js
node_js:
  - "0.8"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make alltests
branches:
  only:
    - master
notifications:
  recipients:
    - boemianrapsodi@gmail.com
  email:
    on_success: change
    on_failure: always
